- name: Populating container images into internal registry
  hosts: workstations
  become: false
  remote_user: student
  gather_facts: false
  vars:
    images:
      postgresql:
        image: registry.ocp4.example.com:8443/postgres:13
        filename: postgresql.tar.gz
      airflow:
        image: registry.ocp4.example.com:8443/apache/airflow:3.0.3
        filename: airflow.tar.gz
      python:
        image: registry.ocp4.example.com:8443/ubi9/python3.9
        filename: python.tar.gz

  tasks:
  - name: Log into each container registry on students workstation
    ansible.builtin.command: 
      cmd: podman login registry.ocp4.example.com:8443 -u {{ quay_username }} -p {{ quay_password }}

  - name: Pushing containers 
    ansible.builtin.include_tasks: container_push.yaml
    loop: "{{ lookup('dict',images) }}"
    loop_control:
      loop_var: current_item
          
  - name: Make {{ item }} Repository public
    infra.quay_configuration.quay_repository:
      quay_host: "https://registry.ocp4.example.com:8443"  # Or your private Quay instance URL
      quay_username: "{{ quay_username }}"        # Your Quay OAuth access token
      quay_password: "{{ quay_password }}"
      name: "{{ item }}"
      visibility: "public"
      state: present
    loop:
      - library/postgres
      - apache/airflow
      - ubi9/python3.9

